import { describe, it, expect } from "vitest";
import { renderMarkdown } from "../renderer/markdown.js";
import { renderJson } from "../renderer/json.js";
import { makeFinding, makeDomainReport } from "./fixtures.js";
import type { ConsolidatedReport } from "../types.js";

function makeConsolidatedReport(overrides: Partial<ConsolidatedReport> = {}): ConsolidatedReport {
  const securityReport = makeDomainReport({
    domain: "security",
    score: 72,
    summary: "1 high, 1 medium",
    findings: [
      makeFinding({ id: "SEC-001", severity: "high", title: "Hardcoded API key", confidence: 0.9 }),
      makeFinding({ id: "SEC-002", severity: "medium", title: "Missing CSP header", rule: "missing-csp", confidence: 0.7 }),
    ],
  });

  const testsReport = makeDomainReport({
    domain: "tests",
    score: 85,
    summary: "1 medium",
    findings: [
      makeFinding({ id: "TST-001", severity: "medium", title: "Low branch coverage", domain: "tests", rule: "low-branch-coverage", confidence: 1.0 }),
    ],
    metadata: { agent: "audit-tests", timestamp: "2026-02-27T10:00:00.000Z" },
  });

  return {
    overall_score: 78,
    grade: "B",
    summary: "Overall score: 78/100 (Grade B). Findings: 1 high, 2 medium.",
    domain_reports: [securityReport, testsReport],
    top_findings: [
      makeFinding({ id: "SEC-001", severity: "high", title: "Hardcoded API key", confidence: 0.9, recommendation: "Move secret to environment variable." }),
      makeFinding({ id: "SEC-002", severity: "medium", title: "Missing CSP header", rule: "missing-csp", confidence: 0.7, recommendation: "Add Content-Security-Policy header." }),
      makeFinding({ id: "TST-001", severity: "medium", title: "Low branch coverage", domain: "tests", rule: "low-branch-coverage", confidence: 1.0, recommendation: "Add tests for uncovered branches." }),
    ],
    statistics: {
      total_findings: 3,
      by_severity: { critical: 0, high: 1, medium: 2, low: 0, info: 0 },
      by_domain: { security: 2, tests: 1 },
    },
    metadata: {
      timestamp: "2026-02-27T10:05:00.000Z",
      target: "/projects/my-app",
      profile: "generic",
      duration_ms: 4500,
      agents_invoked: ["audit-security", "audit-tests"],
    },
    ...overrides,
  };
}

describe("renderMarkdown", () => {
  it("generates a complete Markdown report", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("# Inspectra Audit Report");
    expect(md).toContain("## Executive Summary");
    expect(md).toContain("78/100");
    expect(md).toContain("Grade **B**");
  });

  it("includes domain scores table", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("## Domain Scores");
    expect(md).toContain("Security");
    expect(md).toContain("72/100");
    expect(md).toContain("Tests");
    expect(md).toContain("85/100");
  });

  it("includes top priority findings with severity icons", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("## Top Priority Findings");
    expect(md).toContain("SEC-001");
    expect(md).toContain("🟠"); // high severity icon
    expect(md).toContain("Hardcoded API key");
  });

  it("includes domain details grouped by severity", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("## Domain Details");
    expect(md).toContain("### Security (72/100)");
    expect(md).toContain("#### 🟠 High (1)");
    expect(md).toContain("#### 🟡 Medium (1)");
  });

  it("includes recommended actions", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("## Recommended Actions");
    expect(md).toContain("1.");
  });

  it("includes metadata footer", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("Generated by Inspectra");
    expect(md).toContain("/projects/my-app");
    expect(md).toContain("generic");
    expect(md).toContain("4.5s");
  });

  it("handles report with no findings", () => {
    const report = makeConsolidatedReport({
      overall_score: 100,
      grade: "A",
      top_findings: [],
      domain_reports: [
        makeDomainReport({ domain: "security", score: 100, findings: [], summary: "No issues found" }),
      ],
      statistics: { total_findings: 0, by_severity: { critical: 0, high: 0, medium: 0, low: 0, info: 0 } },
    });

    const md = renderMarkdown(report);
    expect(md).toContain("100/100");
    expect(md).toContain("Grade **A**");
    expect(md).toContain("No findings");
  });
});

describe("renderJson", () => {
  it("returns valid JSON string", () => {
    const report = makeConsolidatedReport();
    const json = renderJson(report);
    const parsed = JSON.parse(json);

    expect(parsed.overall_score).toBe(78);
    expect(parsed.grade).toBe("B");
    expect(parsed.top_findings).toHaveLength(3);
  });

  it("preserves all fields", () => {
    const report = makeConsolidatedReport();
    const json = renderJson(report);
    const parsed = JSON.parse(json);

    expect(parsed.metadata.target).toBe("/projects/my-app");
    expect(parsed.domain_reports).toHaveLength(2);
    expect(parsed.statistics.total_findings).toBe(3);
  });
});
