import { describe, it, expect } from "vitest";
import { renderMarkdown } from "../renderer/markdown.js";
import { renderJson } from "../renderer/json.js";
import { renderSarif } from "../renderer/sarif.js";
import { makeFinding, makeDomainReport } from "./fixtures.js";
import type { ConsolidatedReport } from "../types.js";

function makeConsolidatedReport(overrides: Partial<ConsolidatedReport> = {}): ConsolidatedReport {
  const securityReport = makeDomainReport({
    domain: "security",
    score: 72,
    summary: "1 high, 1 medium",
    findings: [
      makeFinding({ id: "SEC-001", severity: "high", title: "Hardcoded API key", confidence: 0.9 }),
      makeFinding({
        id: "SEC-002",
        severity: "medium",
        title: "Missing CSP header",
        rule: "missing-csp",
        confidence: 0.7,
      }),
    ],
  });

  const testsReport = makeDomainReport({
    domain: "tests",
    score: 85,
    summary: "1 medium",
    findings: [
      makeFinding({
        id: "TST-001",
        severity: "medium",
        title: "Low branch coverage",
        domain: "tests",
        rule: "low-branch-coverage",
        confidence: 1.0,
      }),
    ],
    metadata: { agent: "audit-tests", timestamp: "2026-02-27T10:00:00.000Z" },
  });

  return {
    overall_score: 78,
    grade: "B",
    summary: "Overall score: 78/100 (Grade B). Findings: 1 high, 2 medium.",
    domain_reports: [securityReport, testsReport],
    top_findings: [
      makeFinding({
        id: "SEC-001",
        severity: "high",
        title: "Hardcoded API key",
        confidence: 0.9,
        recommendation: "Move secret to environment variable.",
      }),
      makeFinding({
        id: "SEC-002",
        severity: "medium",
        title: "Missing CSP header",
        rule: "missing-csp",
        confidence: 0.7,
        recommendation: "Add Content-Security-Policy header.",
      }),
      makeFinding({
        id: "TST-001",
        severity: "medium",
        title: "Low branch coverage",
        domain: "tests",
        rule: "low-branch-coverage",
        confidence: 1.0,
        recommendation: "Add tests for uncovered branches.",
      }),
    ],
    statistics: {
      total_findings: 3,
      by_severity: { critical: 0, high: 1, medium: 2, low: 0, info: 0 },
      by_domain: { security: 2, tests: 1 },
    },
    metadata: {
      timestamp: "2026-02-27T10:05:00.000Z",
      target: "/projects/my-app",
      profile: "generic",
      duration_ms: 4500,
      domains_audited: ["security", "tests"],
    },
    ...overrides,
  };
}

describe("renderMarkdown", () => {
  it("generates a complete Markdown report", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("# Inspectra Audit Report");
    expect(md).toContain("## Executive Summary");
    expect(md).toContain("78/100");
    expect(md).toContain("Grade **B**");
  });

  it("includes domain scores table", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("## Domain Scores");
    expect(md).toContain("Security");
    expect(md).toContain("72/100");
    expect(md).toContain("Tests");
    expect(md).toContain("85/100");
  });

  it("includes top priority findings with severity icons", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("## Top Priority Findings");
    expect(md).toContain("SEC-001");
    expect(md).toContain("🟠"); // high severity icon
    expect(md).toContain("Hardcoded API key");
  });

  it("includes domain details grouped by severity", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("## Domain Details");
    expect(md).toContain("### Security (72/100)");
    expect(md).toContain("#### 🟠 High (1)");
    expect(md).toContain("#### 🟡 Medium (1)");
  });

  it("includes recommended actions", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("## Recommended Actions");
    expect(md).toContain("1.");
  });

  it("includes metadata footer", () => {
    const report = makeConsolidatedReport();
    const md = renderMarkdown(report);

    expect(md).toContain("Generated by Inspectra");
    expect(md).toContain("/projects/my-app");
    expect(md).toContain("generic");
    expect(md).toContain("4.5s");
  });

  it("handles report with no findings", () => {
    const report = makeConsolidatedReport({
      overall_score: 100,
      grade: "A",
      top_findings: [],
      domain_reports: [makeDomainReport({ domain: "security", score: 100, findings: [], summary: "No issues found" })],
      statistics: { total_findings: 0, by_severity: { critical: 0, high: 0, medium: 0, low: 0, info: 0 } },
    });

    const md = renderMarkdown(report);
    expect(md).toContain("100/100");
    expect(md).toContain("Grade **A**");
    expect(md).toContain("No findings");
  });
});

describe("renderJson", () => {
  it("returns valid JSON string", () => {
    const report = makeConsolidatedReport();
    const json = renderJson(report);
    const parsed = JSON.parse(json);

    expect(parsed.overall_score).toBe(78);
    expect(parsed.grade).toBe("B");
    expect(parsed.top_findings).toHaveLength(3);
  });

  it("preserves all fields", () => {
    const report = makeConsolidatedReport();
    const json = renderJson(report);
    const parsed = JSON.parse(json);

    expect(parsed.metadata.target).toBe("/projects/my-app");
    expect(parsed.domain_reports).toHaveLength(2);
    expect(parsed.statistics.total_findings).toBe(3);
  });
});

describe("renderSarif", () => {
  it("produces valid SARIF v2.1.0 structure", () => {
    const report = makeConsolidatedReport();
    const output = renderSarif(report);
    const sarif = JSON.parse(output);

    expect(sarif.version).toBe("2.1.0");
    expect(sarif.$schema).toContain("sarif-schema-2.1.0");
    expect(sarif.runs).toHaveLength(1);
    expect(sarif.runs[0].tool.driver.name).toBe("Inspectra");
  });

  it("maps findings to SARIF results", () => {
    const report = makeConsolidatedReport();
    const sarif = JSON.parse(renderSarif(report));

    const results = sarif.runs[0].results;
    expect(results).toHaveLength(3);
    expect(results[0].ruleId).toBe("no-hardcoded-secrets");
    expect(results[1].ruleId).toBe("missing-csp");
    expect(results[2].ruleId).toBe("low-branch-coverage");
  });

  it("maps severity to correct SARIF levels", () => {
    const report = makeConsolidatedReport();
    const sarif = JSON.parse(renderSarif(report));

    const results = sarif.runs[0].results;
    expect(results[0].level).toBe("error");
    expect(results[1].level).toBe("warning");
    expect(results[2].level).toBe("warning");
  });

  it("includes evidence as locations", () => {
    const finding = makeFinding({
      id: "SEC-099",
      severity: "critical",
      title: "Secret in code",
      evidence: [{ file: "src/config.ts", line: 42, snippet: "apiKey = '...'" }],
    });
    const report = makeConsolidatedReport({
      domain_reports: [makeDomainReport({ domain: "security", score: 50, findings: [finding] })],
    });
    const sarif = JSON.parse(renderSarif(report));

    const loc = sarif.runs[0].results[0].locations[0];
    expect(loc.physicalLocation.artifactLocation.uri).toBe("src/config.ts");
    expect(loc.physicalLocation.region.startLine).toBe(42);
  });

  it("deduplicates rules in the driver", () => {
    const report = makeConsolidatedReport();
    const sarif = JSON.parse(renderSarif(report));

    const ruleIds = sarif.runs[0].tool.driver.rules.map((r: { id: string }) => r.id);
    expect(new Set(ruleIds).size).toBe(ruleIds.length);
  });

  it("includes domain and confidence in result properties", () => {
    const report = makeConsolidatedReport();
    const sarif = JSON.parse(renderSarif(report));

    const props = sarif.runs[0].results[0].properties;
    expect(props.domain).toBe("security");
    expect(props.confidence).toBe(0.9);
    expect(props.severity).toBe("high");
  });

  it("handles empty findings", () => {
    const report = makeConsolidatedReport({
      domain_reports: [makeDomainReport({ domain: "security", score: 100, findings: [] })],
    });
    const sarif = JSON.parse(renderSarif(report));

    expect(sarif.runs[0].results).toHaveLength(0);
    expect(sarif.runs[0].tool.driver.rules).toHaveLength(0);
  });
});
