import { describe, it, expect } from "vitest";
import { renderHtml } from "../renderer/html.js";
import { buildTrendEntry, analyzeTrend, renderTrendMarkdown, type TrendEntry } from "../renderer/trend.js";
import { compareReports, renderComparisonMarkdown } from "../renderer/compare.js";
import { makeFinding, makeDomainReport } from "./fixtures.js";
import type { ConsolidatedReport } from "../types.js";

// ─── Test Helpers ────────────────────────────────────────────────────────────

function makeReport(overrides: Partial<ConsolidatedReport> = {}): ConsolidatedReport {
  return {
    overall_score: 78,
    grade: "B",
    summary: "Overall score: 78/100",
    domain_reports: [
      makeDomainReport({
        domain: "security",
        score: 72,
        findings: [
          makeFinding({ id: "SEC-001", severity: "high", title: "Hardcoded API key" }),
          makeFinding({ id: "SEC-002", severity: "medium", title: "Missing CSP", rule: "missing-csp" }),
        ],
      }),
      makeDomainReport({
        domain: "tests",
        score: 85,
        findings: [
          makeFinding({ id: "TST-001", severity: "medium", title: "Low coverage", domain: "tests", rule: "low-cov" }),
        ],
      }),
    ],
    top_findings: [
      makeFinding({ id: "SEC-001", severity: "high", title: "Hardcoded API key", recommendation: "Use env vars" }),
    ],
    statistics: {
      total_findings: 3,
      by_severity: { critical: 0, high: 1, medium: 2, low: 0, info: 0 },
      by_domain: { security: 2, tests: 1 },
    },
    metadata: {
      timestamp: "2026-03-03T10:00:00.000Z",
      target: "/projects/my-app",
      profile: "generic",
      duration_ms: 4200,
      agents_invoked: ["audit-security", "audit-tests"],
    },
    ...overrides,
  };
}

// ─── renderHtml ──────────────────────────────────────────────────────────────

describe("renderHtml", () => {
  it("produces a valid HTML document", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<html");
    expect(html).toContain("</html>");
  });

  it("includes the report title", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("Inspectra Audit Report");
  });

  it("includes the target project in the page title", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("/projects/my-app");
  });

  it("includes embedded CSS (no external stylesheet)", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("<style>");
    expect(html).toContain("</style>");
    expect(html).not.toContain('<link rel="stylesheet"');
  });

  it("renders the overall score", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("78");
    expect(html).toContain("out of 100");
  });

  it("renders the grade badge", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("grade-badge");
    expect(html).toContain(">B<");
  });

  it("renders domain cards for each domain", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("security");
    expect(html).toContain("tests");
    expect(html).toContain("72");
    expect(html).toContain("85");
  });

  it("renders severity chart bars", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("Findings by Severity");
    expect(html).toContain("Critical");
    expect(html).toContain("High");
    expect(html).toContain("Medium");
  });

  it("renders top findings section", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("Top Priority Findings");
    expect(html).toContain("SEC-001");
    expect(html).toContain("Hardcoded API key");
  });

  it("renders finding recommendation with lightbulb icon", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("finding-fix");
    expect(html).toContain("Use env vars");
  });

  it("renders domain sections with all findings", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("SEC-002");
    expect(html).toContain("Missing CSP");
    expect(html).toContain("TST-001");
  });

  it("renders metadata footer", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("Generated by Inspectra");
    expect(html).toContain("2026-03-03T10:00:00.000Z");
  });

  it("renders duration in the score card", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("4.2s");
  });

  it("handles report with no findings gracefully", () => {
    const emptyReport = makeReport({
      overall_score: 100,
      grade: "A",
      top_findings: [],
      statistics: { total_findings: 0, by_severity: { critical: 0, high: 0, medium: 0, low: 0, info: 0 } },
      domain_reports: [makeDomainReport({ domain: "security", score: 100, findings: [] })],
    });

    const html = renderHtml(emptyReport);

    expect(html).toContain("100");
    expect(html).toContain("No findings");
  });

  it("escapes HTML special characters in project path", () => {
    const report = makeReport({
      metadata: {
        timestamp: "2026-03-03T10:00:00.000Z",
        target: '<script>alert("xss")</script>',
        profile: "generic",
      },
    });

    const html = renderHtml(report);

    expect(html).not.toContain("<script>");
    expect(html).toContain("&lt;script&gt;");
  });

  it("renders SVG score ring", () => {
    const html = renderHtml(makeReport());

    expect(html).toContain("<svg");
    expect(html).toContain("<circle");
  });
});

// ─── Trend ───────────────────────────────────────────────────────────────────

describe("buildTrendEntry", () => {
  it("extracts score and grade from a report", () => {
    const entry = buildTrendEntry(makeReport());

    expect(entry.overall_score).toBe(78);
    expect(entry.grade).toBe("B");
    expect(entry.timestamp).toBe("2026-03-03T10:00:00.000Z");
  });

  it("captures total findings count", () => {
    const entry = buildTrendEntry(makeReport());

    expect(entry.total_findings).toBe(3);
  });

  it("captures per-domain scores", () => {
    const entry = buildTrendEntry(makeReport());

    expect(entry.domain_scores["security"]).toBe(72);
    expect(entry.domain_scores["tests"]).toBe(85);
  });

  it("defaults total_findings to 0 when statistics is absent", () => {
    const report = makeReport({ statistics: undefined });
    const entry = buildTrendEntry(report);

    expect(entry.total_findings).toBe(0);
  });
});

describe("analyzeTrend", () => {
  const baseEntry: TrendEntry = {
    timestamp: "2026-01-01T10:00:00.000Z",
    overall_score: 60,
    grade: "C",
    total_findings: 10,
    domain_scores: { security: 55 },
  };

  it("returns stable for empty entries", () => {
    const trend = analyzeTrend([]);

    expect(trend.direction).toBe("stable");
    expect(trend.entries).toHaveLength(0);
    expect(trend.averageScore).toBe(0);
  });

  it("returns stable for a single entry", () => {
    const trend = analyzeTrend([baseEntry]);

    expect(trend.direction).toBe("stable");
    expect(trend.averageScore).toBe(60);
    expect(trend.bestScore).toBe(60);
    expect(trend.worstScore).toBe(60);
  });

  it("detects improving trend", () => {
    const entries: TrendEntry[] = [
      { ...baseEntry, timestamp: "2026-01-01T00:00:00.000Z", overall_score: 50 },
      { ...baseEntry, timestamp: "2026-02-01T00:00:00.000Z", overall_score: 65 },
      { ...baseEntry, timestamp: "2026-03-01T00:00:00.000Z", overall_score: 75 },
    ];

    const trend = analyzeTrend(entries);

    expect(trend.direction).toBe("improving");
    expect(trend.scoreChange).toBe(25);
  });

  it("detects declining trend", () => {
    const entries: TrendEntry[] = [
      { ...baseEntry, timestamp: "2026-01-01T00:00:00.000Z", overall_score: 90 },
      { ...baseEntry, timestamp: "2026-02-01T00:00:00.000Z", overall_score: 80 },
      { ...baseEntry, timestamp: "2026-03-01T00:00:00.000Z", overall_score: 70 },
    ];

    const trend = analyzeTrend(entries);

    expect(trend.direction).toBe("declining");
    expect(trend.scoreChange).toBe(-20);
  });

  it("detects stable trend when variation is small", () => {
    const entries: TrendEntry[] = [
      { ...baseEntry, timestamp: "2026-01-01T00:00:00.000Z", overall_score: 80 },
      { ...baseEntry, timestamp: "2026-02-01T00:00:00.000Z", overall_score: 81 },
      { ...baseEntry, timestamp: "2026-03-01T00:00:00.000Z", overall_score: 80 },
    ];

    const trend = analyzeTrend(entries);

    expect(trend.direction).toBe("stable");
  });

  it("sorts entries by timestamp", () => {
    const entries: TrendEntry[] = [
      { ...baseEntry, timestamp: "2026-03-01T00:00:00.000Z", overall_score: 90 },
      { ...baseEntry, timestamp: "2026-01-01T00:00:00.000Z", overall_score: 60 },
      { ...baseEntry, timestamp: "2026-02-01T00:00:00.000Z", overall_score: 75 },
    ];

    const trend = analyzeTrend(entries);

    expect(trend.entries[0]?.timestamp).toBe("2026-01-01T00:00:00.000Z");
    expect(trend.entries[2]?.timestamp).toBe("2026-03-01T00:00:00.000Z");
  });

  it("computes correct best and worst scores", () => {
    const entries: TrendEntry[] = [
      { ...baseEntry, timestamp: "2026-01-01T00:00:00.000Z", overall_score: 42 },
      { ...baseEntry, timestamp: "2026-02-01T00:00:00.000Z", overall_score: 88 },
      { ...baseEntry, timestamp: "2026-03-01T00:00:00.000Z", overall_score: 65 },
    ];

    const trend = analyzeTrend(entries);

    expect(trend.bestScore).toBe(88);
    expect(trend.worstScore).toBe(42);
  });
});

describe("renderTrendMarkdown", () => {
  it("renders 'no data' for empty trend", () => {
    const trend = analyzeTrend([]);
    const md = renderTrendMarkdown(trend);

    expect(md).toContain("No trend data");
  });

  it("includes score trend header", () => {
    const entries: TrendEntry[] = [
      {
        timestamp: "2026-01-01T00:00:00.000Z",
        overall_score: 70,
        grade: "C",
        total_findings: 5,
        domain_scores: {},
      },
      {
        timestamp: "2026-02-01T00:00:00.000Z",
        overall_score: 80,
        grade: "B",
        total_findings: 3,
        domain_scores: {},
      },
    ];
    const md = renderTrendMarkdown(analyzeTrend(entries));

    expect(md).toContain("## Score Trend");
    expect(md).toContain("Improving");
  });

  it("includes history table", () => {
    const entries: TrendEntry[] = [
      {
        timestamp: "2026-01-15T00:00:00.000Z",
        overall_score: 75,
        grade: "B",
        total_findings: 4,
        domain_scores: {},
      },
    ];
    const md = renderTrendMarkdown(analyzeTrend(entries));

    expect(md).toContain("### History");
    expect(md).toContain("2026-01-15");
    expect(md).toContain("75");
  });
});

// ─── Compare ─────────────────────────────────────────────────────────────────

describe("compareReports", () => {
  it("computes overall delta", () => {
    const reportA = makeReport({ overall_score: 85, grade: "B" });
    const reportB = makeReport({ overall_score: 70, grade: "C" });

    const result = compareReports(reportA, reportB);

    expect(result.overallDelta).toBe(15);
  });

  it("reports both scores and grades", () => {
    const reportA = makeReport({ overall_score: 90, grade: "A" });
    const reportB = makeReport({ overall_score: 60, grade: "C" });

    const result = compareReports(reportA, reportB);

    expect(result.reportA.score).toBe(90);
    expect(result.reportA.grade).toBe("A");
    expect(result.reportB.score).toBe(60);
    expect(result.reportB.grade).toBe("C");
  });

  it("uses custom labels", () => {
    const result = compareReports(makeReport(), makeReport(), "Before", "After");

    expect(result.reportA.label).toBe("Before");
    expect(result.reportB.label).toBe("After");
  });

  it("computes per-domain comparison", () => {
    const reportA = makeReport();
    const reportB = makeReport({
      domain_reports: [
        makeDomainReport({ domain: "security", score: 60 }),
        makeDomainReport({ domain: "tests", score: 90 }),
      ],
    });

    const result = compareReports(reportA, reportB);
    const secDomain = result.domains.find((d) => d.domain === "security");

    expect(secDomain?.scoreA).toBe(72);
    expect(secDomain?.scoreB).toBe(60);
    expect(secDomain?.delta).toBe(12);
  });

  it("includes domains present in only one report", () => {
    const reportA = makeReport({
      domain_reports: [
        makeDomainReport({ domain: "security", score: 72 }),
        makeDomainReport({ domain: "conventions", score: 80, findings: [] }),
      ],
    });
    const reportB = makeReport({
      domain_reports: [makeDomainReport({ domain: "security", score: 60 })],
    });

    const result = compareReports(reportA, reportB);
    const convDomain = result.domains.find((d) => d.domain === "conventions");

    expect(convDomain).toBeDefined();
    expect(convDomain?.scoreA).toBe(80);
    expect(convDomain?.scoreB).toBe(100); // defaulted
  });

  it("identifies added findings (in A but not B)", () => {
    const reportA = makeReport({
      domain_reports: [
        makeDomainReport({
          domain: "security",
          findings: [
            makeFinding({ id: "SEC-001" }),
            makeFinding({ id: "SEC-099", title: "New issue" }),
          ],
        }),
      ],
    });
    const reportB = makeReport({
      domain_reports: [
        makeDomainReport({ domain: "security", findings: [makeFinding({ id: "SEC-001" })] }),
      ],
    });

    const result = compareReports(reportA, reportB);

    expect(result.added).toHaveLength(1);
    expect(result.added[0]?.id).toBe("SEC-099");
  });

  it("identifies removed findings (in B but not A)", () => {
    const reportA = makeReport({
      domain_reports: [
        makeDomainReport({ domain: "security", findings: [makeFinding({ id: "SEC-001" })] }),
      ],
    });
    const reportB = makeReport({
      domain_reports: [
        makeDomainReport({
          domain: "security",
          findings: [
            makeFinding({ id: "SEC-001" }),
            makeFinding({ id: "SEC-042", title: "Old issue", rule: "old" }),
          ],
        }),
      ],
    });

    const result = compareReports(reportA, reportB);

    expect(result.removed).toHaveLength(1);
    expect(result.removed[0]?.id).toBe("SEC-042");
  });

  it("identifies unchanged findings (present in both)", () => {
    const reportA = makeReport({
      domain_reports: [
        makeDomainReport({ domain: "security", findings: [makeFinding({ id: "SEC-001" })] }),
      ],
    });
    const reportB = makeReport({
      domain_reports: [
        makeDomainReport({ domain: "security", findings: [makeFinding({ id: "SEC-001" })] }),
      ],
    });

    const result = compareReports(reportA, reportB);

    expect(result.unchanged).toHaveLength(1);
    expect(result.unchanged[0]?.id).toBe("SEC-001");
  });
});

describe("renderComparisonMarkdown", () => {
  it("includes comparison header", () => {
    const result = compareReports(makeReport(), makeReport());
    const md = renderComparisonMarkdown(result);

    expect(md).toContain("## Audit Comparison");
  });

  it("includes summary table with both scores", () => {
    const result = compareReports(
      makeReport({ overall_score: 85, grade: "B" }),
      makeReport({ overall_score: 70, grade: "C" }),
      "v2.0",
      "v1.0",
    );
    const md = renderComparisonMarkdown(result);

    expect(md).toContain("v2.0");
    expect(md).toContain("v1.0");
    expect(md).toContain("85/100");
    expect(md).toContain("70/100");
    expect(md).toContain("+15");
  });

  it("includes domain comparison table", () => {
    const result = compareReports(makeReport(), makeReport());
    const md = renderComparisonMarkdown(result);

    expect(md).toContain("### Domain Comparison");
    expect(md).toContain("Security");
  });

  it("shows added findings", () => {
    const reportA = makeReport({
      domain_reports: [
        makeDomainReport({
          domain: "security",
          findings: [makeFinding({ id: "SEC-099", title: "New vuln" })],
        }),
      ],
    });

    const result = compareReports(reportA, makeReport({ domain_reports: [] }));
    const md = renderComparisonMarkdown(result);

    expect(md).toContain("Added Findings");
    expect(md).toContain("SEC-099");
  });

  it("shows removed findings with strikethrough", () => {
    const reportB = makeReport({
      domain_reports: [
        makeDomainReport({
          domain: "security",
          findings: [makeFinding({ id: "SEC-042", title: "Old vuln" })],
        }),
      ],
    });

    const result = compareReports(makeReport({ domain_reports: [] }), reportB);
    const md = renderComparisonMarkdown(result);

    expect(md).toContain("Removed Findings");
    expect(md).toContain("~~SEC-042");
  });

  it("shows 'None' when no added findings", () => {
    const result = compareReports(makeReport(), makeReport());
    const md = renderComparisonMarkdown(result);

    expect(md).toContain("_None_");
  });
});
