import type { ConsolidatedReport, Finding } from "../types.js";

const SEVERITY_ICONS: Record<string, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
  info: "⚪",
};

export function renderMarkdown(report: ConsolidatedReport): string {
  const lines: string[] = [];

  lines.push("# Inspectra Audit Report");
  lines.push("");

  lines.push(renderExecutiveSummary(report));
  lines.push(renderDomainScores(report));
  lines.push(renderTopFindings(report.top_findings));
  lines.push(renderDomainDetails(report));
  lines.push(renderRecommendations(report));
  lines.push(renderMetadata(report));

  return lines.join("\n");
}

function renderExecutiveSummary(report: ConsolidatedReport): string {
  const { overall_score, grade, statistics } = report;
  const sev = statistics?.by_severity;

  const lines: string[] = [];
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| **Overall Score** | **${overall_score}/100** (Grade **${grade}**) |`);
  lines.push(`| Total Findings | ${statistics?.total_findings ?? 0} |`);
  if (sev) {
    lines.push(`| Critical | ${sev.critical} |`);
    lines.push(`| High | ${sev.high} |`);
    lines.push(`| Medium | ${sev.medium} |`);
    lines.push(`| Low | ${sev.low} |`);
    lines.push(`| Info | ${sev.info} |`);
  }
  lines.push("");

  return lines.join("\n");
}

function renderDomainScores(report: ConsolidatedReport): string {
  const lines: string[] = [];
  lines.push("## Domain Scores");
  lines.push("");
  lines.push("| Domain | Score | Findings | Summary |");
  lines.push("|--------|-------|----------|---------|");

  for (const dr of report.domain_reports) {
    const findingCount = dr.findings.length;
    const bar = renderScoreBar(dr.score);
    lines.push(`| ${capitalize(dr.domain)} | ${bar} ${dr.score}/100 | ${findingCount} | ${dr.summary} |`);
  }

  lines.push("");
  return lines.join("\n");
}

function renderTopFindings(findings: Finding[]): string {
  if (findings.length === 0) return "";

  const lines: string[] = [];
  lines.push("## Top Priority Findings");
  lines.push("");

  for (const f of findings) {
    const icon = SEVERITY_ICONS[f.severity] ?? "⚪";
    const location = f.evidence?.[0]
      ? `\`${f.evidence[0].file}${f.evidence[0].line ? `:${f.evidence[0].line}` : ""}\``
      : "_no location_";

    lines.push(`### ${icon} ${f.id} — ${f.title}`);
    lines.push("");
    lines.push(`- **Severity:** ${f.severity} | **Confidence:** ${(f.confidence * 100).toFixed(0)}% | **Effort:** ${f.effort ?? "unknown"}`);
    lines.push(`- **Location:** ${location}`);
    if (f.description) {
      lines.push(`- **Details:** ${f.description}`);
    }
    if (f.recommendation) {
      lines.push(`- **Fix:** ${f.recommendation}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function renderDomainDetails(report: ConsolidatedReport): string {
  const lines: string[] = [];
  lines.push("## Domain Details");
  lines.push("");

  for (const dr of report.domain_reports) {
    lines.push(`### ${capitalize(dr.domain)} (${dr.score}/100)`);
    lines.push("");

    if (dr.findings.length === 0) {
      lines.push("_No findings — clean!_");
      lines.push("");
      continue;
    }

    const grouped = groupBySeverity(dr.findings);
    for (const [severity, findings] of grouped) {
      const icon = SEVERITY_ICONS[severity] ?? "⚪";
      lines.push(`#### ${icon} ${capitalize(severity)} (${findings.length})`);
      lines.push("");

      for (const f of findings) {
        const location = f.evidence?.[0]?.file ?? "";
        const line = f.evidence?.[0]?.line ? `:${f.evidence[0].line}` : "";
        lines.push(`- **${f.id}** ${f.title} — \`${location}${line}\``);
        if (f.recommendation) {
          lines.push(`  - Fix: ${f.recommendation}`);
        }
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

function renderRecommendations(report: ConsolidatedReport): string {
  const actionable = report.top_findings.filter(
    (f) => f.recommendation && f.severity !== "info"
  );

  if (actionable.length === 0) return "";

  const lines: string[] = [];
  lines.push("## Recommended Actions");
  lines.push("");
  lines.push("Prioritized list of the most impactful fixes:");
  lines.push("");

  for (let i = 0; i < actionable.length; i++) {
    const f = actionable[i];
    lines.push(`${i + 1}. **[${f.severity.toUpperCase()}]** ${f.recommendation} _(${f.id})_`);
  }

  lines.push("");
  return lines.join("\n");
}

function renderMetadata(report: ConsolidatedReport): string {
  const { metadata } = report;
  const lines: string[] = [];
  lines.push("---");
  lines.push("");
  lines.push(`_Generated by Inspectra on ${metadata.timestamp}_`);
  lines.push(`_Target: ${metadata.target} | Profile: ${metadata.profile}_`);
  if (metadata.agents_invoked?.length) {
    lines.push(`_Agents: ${metadata.agents_invoked.join(", ")}_`);
  }
  if (metadata.duration_ms) {
    lines.push(`_Duration: ${(metadata.duration_ms / 1000).toFixed(1)}s_`);
  }
  lines.push("");

  return lines.join("\n");
}

function renderScoreBar(score: number): string {
  const filled = Math.round(score / 10);
  return "█".repeat(filled) + "░".repeat(10 - filled);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function groupBySeverity(findings: Finding[]): [string, Finding[]][] {
  const order = ["critical", "high", "medium", "low", "info"];
  const map = new Map<string, Finding[]>();

  for (const f of findings) {
    const list = map.get(f.severity) ?? [];
    list.push(f);
    map.set(f.severity, list);
  }

  return order.filter((s) => map.has(s)).map((s) => [s, map.get(s)!]);
}
