import { readFile } from "node:fs/promises";
import { join, relative } from "node:path";
import type { Finding } from "../types.js";
import { collectAllFiles, collectSourceFiles } from "../utils/files.js";
import { createIdSequence } from "../utils/id.js";

const LARGE_BUNDLE_WARNING_BYTES = 500 * 1024;
const LARGE_BUNDLE_ERROR_BYTES = 1000 * 1024;

/**
 * Analyze bundle size from common build outputs (`stats.json`, `bundle-stats.json`)
 * and fallback to heavy JS assets in dist/build directories.
 */
export async function analyzeBundleSize(projectDir: string): Promise<Finding[]> {
  const findings: Finding[] = [];
  const nextId = createIdSequence("PRF");

  const statsCandidates = [join(projectDir, "dist", "stats.json"), join(projectDir, "bundle-stats.json")];

  for (const candidate of statsCandidates) {
    try {
      const raw = await readFile(candidate, "utf-8");
      const parsed = JSON.parse(raw) as {
        assets?: Array<{ name?: string; size?: number }>;
      };

      for (const asset of parsed.assets ?? []) {
        if (!asset.name || typeof asset.size !== "number") continue;
        if (asset.size <= LARGE_BUNDLE_WARNING_BYTES) continue;

        findings.push({
          id: nextId(),
          severity: asset.size > LARGE_BUNDLE_ERROR_BYTES ? "high" : "medium",
          title: `Large bundle asset: ${asset.name} (${formatBytes(asset.size)})`,
          description: `Asset size exceeds recommended threshold (${formatBytes(LARGE_BUNDLE_WARNING_BYTES)}).`,
          domain: "performance",
          rule: "bundle-size-threshold",
          confidence: 0.95,
          evidence: [{ file: relative(projectDir, candidate), snippet: `${asset.name}: ${asset.size}` }],
          recommendation: "Apply code splitting, remove unused dependencies, and enable minification/tree-shaking.",
          effort: "medium",
          tags: ["bundle", "build"],
          source: "tool",
        });
      }

      return findings;
    } catch {
      /* try next source */
    }
  }

  const allFiles = await collectAllFiles(projectDir);
  for (const file of allFiles) {
    if (!/[/\\](dist|build|public)[/\\].*\.js$/i.test(file)) continue;
    try {
      const content = await readFile(file, "utf-8");
      const size = Buffer.byteLength(content, "utf8");
      if (size <= LARGE_BUNDLE_ERROR_BYTES) continue;

      findings.push({
        id: nextId(),
        severity: "medium",
        title: `Large built JavaScript file: ${relative(projectDir, file)} (${formatBytes(size)})`,
        description: "Large JS payload can slow download, parse, and execution times.",
        domain: "performance",
        rule: "large-built-asset",
        confidence: 0.8,
        evidence: [{ file: relative(projectDir, file) }],
        recommendation: "Split bundles and lazy-load non-critical code paths.",
        effort: "medium",
        tags: ["bundle", "runtime"],
        source: "tool",
      });
    } catch {
      /* skip unreadable files */
    }
  }

  return findings;
}

/**
 * Parse timing files generated by CI/local build scripts and flag slow builds.
 */
export async function checkBuildTimings(projectDir: string): Promise<Finding[]> {
  const findings: Finding[] = [];
  const nextId = createIdSequence("PRF", 100);

  const candidates = [join(projectDir, "build-metrics.json"), join(projectDir, ".inspectra", "build-timings.json")];

  for (const candidate of candidates) {
    try {
      const raw = await readFile(candidate, "utf-8");
      const parsed = JSON.parse(raw) as {
        average_build_ms?: number;
        p95_build_ms?: number;
      };

      const averageMs = parsed.average_build_ms ?? 0;
      const p95Ms = parsed.p95_build_ms ?? 0;

      if (averageMs > 120_000) {
        findings.push({
          id: nextId(),
          severity: averageMs > 300_000 ? "high" : "medium",
          title: `Slow average build time: ${(averageMs / 1000).toFixed(1)}s`,
          description: "Average build duration is above the recommended threshold (120s).",
          domain: "performance",
          rule: "build-time-average",
          confidence: 0.9,
          evidence: [{ file: relative(projectDir, candidate), snippet: `average_build_ms=${averageMs}` }],
          recommendation: "Profile the build, cache dependencies/artifacts, and optimize heavy steps.",
          effort: "medium",
          tags: ["build", "ci"],
          source: "tool",
        });
      }

      if (p95Ms > 180_000) {
        findings.push({
          id: nextId(),
          severity: "medium",
          title: `Unstable build tail latency (p95): ${(p95Ms / 1000).toFixed(1)}s`,
          description: "P95 build time indicates significant variability and occasional very slow builds.",
          domain: "performance",
          rule: "build-time-p95",
          confidence: 0.85,
          evidence: [{ file: relative(projectDir, candidate), snippet: `p95_build_ms=${p95Ms}` }],
          recommendation: "Stabilize flaky/slow tasks and improve build cache hit rate.",
          effort: "medium",
          tags: ["build", "ci", "stability"],
          source: "tool",
        });
      }

      break;
    } catch {
      /* no timing file */
    }
  }

  return findings;
}

/**
 * Detect likely runtime hotspots through static heuristics (sync I/O and blocking calls).
 */
export async function detectRuntimeMetrics(projectDir: string): Promise<Finding[]> {
  const findings: Finding[] = [];
  const nextId = createIdSequence("PRF", 200);
  const files = await collectSourceFiles(projectDir);

  const patterns: Array<{ regex: RegExp; rule: string; title: string; severity: Finding["severity"] }> = [
    {
      regex: /\b(readFileSync|writeFileSync|readdirSync|statSync)\(/,
      rule: "sync-fs-usage",
      title: "Synchronous filesystem call in source",
      severity: "medium",
    },
    {
      regex: /\b(execSync|spawnSync)\(/,
      rule: "sync-process-usage",
      title: "Synchronous child process call in source",
      severity: "high",
    },
    {
      regex: /\bwhile\s*\(\s*true\s*\)/,
      rule: "potential-infinite-loop",
      title: "Potential unbounded loop detected",
      severity: "medium",
    },
  ];

  // Sync I/O is acceptable in test helpers and fixture builders — exclude them
  const TEST_OR_FIXTURE_PATH = /[/\\](?:__tests__|fixtures)[/\\]|\.(?:test|spec)\.[tj]s$/;

  for (const filePath of files) {
    if (TEST_OR_FIXTURE_PATH.test(filePath)) continue;
    try {
      const content = await readFile(filePath, "utf-8");
      const lines = content.split("\n");

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (!line) continue;

        for (const pattern of patterns) {
          if (!pattern.regex.test(line)) continue;
          findings.push({
            id: nextId(),
            severity: pattern.severity,
            title: `${pattern.title}: ${relative(projectDir, filePath)}`,
            description: "This pattern can block the event loop or degrade runtime responsiveness.",
            domain: "performance",
            rule: pattern.rule,
            confidence: 0.8,
            evidence: [{ file: relative(projectDir, filePath), line: i + 1, snippet: line.trim().slice(0, 120) }],
            recommendation: "Prefer async alternatives and add guards/timeouts for long-running loops.",
            effort: "small",
            tags: ["runtime", "latency"],
            source: "tool",
          });
        }
      }
    } catch {
      /* skip unreadable files */
    }
  }

  return findings;
}

function formatBytes(value: number): string {
  if (value >= 1024 * 1024) return `${(value / (1024 * 1024)).toFixed(2)} MiB`;
  if (value >= 1024) return `${(value / 1024).toFixed(1)} KiB`;
  return `${value} B`;
}
